language: node_js

node_js: stable

addons:
  sonarcloud:
    organization: han-feng-github
    token:
      secure: $SONAR_CLOUD_TOKEN

cache:
  directories:
    - node_modules

script:
  - npm run build
  - npm test

after_success:
  - npx codecov --token=$CODECOV_TOKEN
  - sonar-scanner
  - cat ./coverage/lcov.info | npx codacy-coverage --token $CODACY_PROJECT_TOKEN --username han-feng --accountToken $CODACY_API_TOKEN
