language: node_js

node_js: stable

addons:
  sonarcloud:
    organization: "han-feng-github"
    token:
      secure: $SONAR_CLOUD_TOKEN

cache:
  directories:
    - "node_modules"

branches:
  only:
  - master

script:
  - npm run build
  - npm test

after_success:
  - sonar-scanner
